project:
  type: website

website:
  title: "Yuyao Huang"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      
      
      
      
page-footer:
  right: "&copy; 2026, Yuyao Huang"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""

execute:
  freeze: auto

